Top-Pageの作成
caramelribon/sweets-journal-nuxtjs pull request #1
Opened 2022-10-19 02:31 UTC by caramelribon

## Top Pageの作成
- [x] Tailwind CSSの導入
- [x] Firebaseの導入
- [x] Headerコンポーネントの作成
- [x] Login&Signup機能
- [x] ログインユーザの情報をVuexで管理
- [x] Titleコンポーネント
- [x] Messageコンポーネント
- [x] Footerコンポーネント
- [x] 周辺のお店検索機能
- [x] お気に入り機能
- [x] 気になる機能
- [x] ログインユーザが保存したお店の取得
- [x] お店のランキング表示

2022-10-23 08:34 UTC, golonyataro reviewed
軽くしか見てないんですけどめちゃいいと思います！
ここ省略できるかも！っていう部分の指摘だけしたので改良した方がいいなと思ったら直してみてください！これは違うと思ったら教えてください。
@YuyaImanari
精度の怪しい指摘コメントをした自覚が少しあるので追加で見ておいてほしい🙏

2022-10-23 08:34 UTC, golonyataro commented on components/headerLoginAfter.vue
> +    openBalloon() {
この関数の中身こう書くのはダメ？
`this.userInfo = !this.userInfo`

2022-10-23 08:34 UTC, golonyataro commented on components/headerLoginAfter.vue
> +    closeBalloon() {
これでこと足りないかな
`this.userInfo = false`

2022-10-23 08:34 UTC, golonyataro commented on components/headerLoginAfter.vue
> +      userInfo: false,
変数名あまりよろしくないかも
userInfoっていう変数名だと変数にユーザー情報が入ってるのかなとぱっと見思った
boolean型だから`isUserInfo`とか`isUser`とかにした方が良いかも

2022-10-23 08:34 UTC, golonyataro commented on components/headerLoginAfter.vue
> +    closeBalloon() {
結局trueの場合はfalseにしているし、falseの場合はそのままfalseが入っているから

2022-10-23 08:34 UTC, golonyataro commented on components/headerLoginBefore.vue
> +      userInfoNoLogin: false,
この辺も上のuserInfoと同じかも

2022-10-23 08:34 UTC, golonyataro commented on components/headerLoginBefore.vue
> +    openBalloonNoLogin() {
同上

2022-10-23 08:34 UTC, golonyataro commented on components/headerLoginBefore.vue
> +    closeBalloonNoLogin() {
同上

2022-10-23 08:34 UTC, golonyataro commented on services/firebaseService.js
> +          if (!doc.data()) {
if内の処理が軽い時は{}を省略してもいいかも
1文で書けるので
`if (!doc.data()) return;`

2022-10-23 08:34 UTC, golonyataro commented on services/firebaseService.js
> +          if (!doc.data()) {
同上

2022-10-23 08:34 UTC, golonyataro commented on services/firebaseService.js
> +  if (action === 'favorite') {
if文の上の処理と下の処理ほぼ同じ事をやっているからまとめた方が見やすいと思う！

2022-10-23 08:34 UTC, golonyataro commented on services/firebaseService.js
> +      bookmark_count: 0,
これでまとめられそう
```
...
favorite_count: action === 'favorite' ? 1 : 0
bookmark_count: action === 'favorite' ? 0 : 1
...
```

2022-10-23 08:34 UTC, golonyataro commented on services/firebaseService.js
> +  if (action === 'favorite') {
これもほぼ同じ事を2回書いているから
```
const assignRef = action === 'favorite' ? favRef : bmRef;
assignRef.doc().set({
  user_id: userId,
  place_id: placeId,
  created_at: firebase.firestore.FieldValue.serverTimestamp(),
});    
```
こんな感じで定義すると良いかも

2022-10-24 02:32 UTC, YuyaImanari requested changes
@caramelribon 口うるさく書いてしまった🙇‍♂️
わからないこととか、不満とかあったらバンバン言って欲しい！

@golonyataro レビューサンキュ、補足とかしたけどバッチリだった！

2022-10-24 02:32 UTC, YuyaImanari commented on components/appRanking.vue
> +      console.log("Can not get data of favorite ranking", err);
エラーが `catch` されると `rankingFav` は null になる。
そうすると、238行目の `rankingFav.length` が `Cannot read property "length" of undefined` というエラーを吐くはず。

### このエラーを防ぐための話

`getRankingTop("favorite").catch()` はこれ全体で Promise Function であり、この関数の戻り値が `rankingFav` に代入される。
- `getRankingTop("favorite")` で例外が発生しなかった場合は、`getRankingTop("favorite")` の戻り値が `getRankingTop("favorite").catch()` の戻り値となる。
- 一方、`getRankingTop("favorite")` で例外が発生した場合は、`catch(Func)` の `Func` の戻り値が `getRankingTop("favorite").catch()` の戻り値となる。現状のコードだと、236行目近辺で戻り値の定義がないので、`undefined` が `rankingFav` に代入されてしまう。

### もう1つの解決策

`getRankingTop("favorite")` が正常終了した場合は `.then()` へ、エラーが発生した場合は `.catch()` へ行くのは知っていると思う。だから、238~252行目を `.then()` に含めれば、上のエラーはなくなる。（なぜなら、`rankingFav` は `.then()` の中でしか使わないので、`.catch()` で戻り値を設定する必要がなくなるから）

2022-10-24 02:32 UTC, YuyaImanari commented on components/appRanking.vue
> +    for (let i = 0; i < rankingFav.length; i += 1) {
この書き方でも正常に処理されるはずなので、かっこいいコードを書くためのアドバイス。

### `forEach()`

大半の for 文は `forEach()` に置き換えられる。もちろんインデックス番号も取れる。
[Array.prototype.forEach() - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)
「大半」と書いたのは、for 文中で非同期処理をしたいときだけは `forEach()` で置き換えられないのでそれだけは覚えておいてください（結構大事）

### `map()`

配列に対して for を回して、最後に空配列に順々に `push` する処理は、`map()` で置き換えられる。
`map()` の使い方はググってみて！わからなければ聞いて〜

2022-10-24 02:32 UTC, YuyaImanari commented on components/headerLoginAfter.vue
> +              <router-link
Nuxt.js では `router-link` の代わりに `nuxt-link` もしくは `n-link` を使います！
https://www.soudegesu.com/post/javascript/nuxt-page-link/

2022-10-24 02:32 UTC, YuyaImanari commented on components/headerLoginAfter.vue
> +      userInfo: false,
社内でも変数名に関しての統一規格みたいなのがないので、絶対これ！みたいな基準はないけど、本田が言う通り、この変数名は不適切。

> `userInfo` っていう変数名だと変数にユーザー情報が入ってるのかなとぱっと見思った

↑まさにこれ。

迷ったら [このQiita](https://qiita.com/YutaManaka/items/62dda256bb7ba6c08399) 読んで欲しい。
今回は「表示/非表示のフラグ」だから、`showUserBalloon` とか `showUserName` とかが良いと思う！

2022-10-24 02:32 UTC, YuyaImanari commented on components/headerLoginAfter.vue
> +    openBalloon() {
本田の指摘はもっとも。

そもそもメソッド名が不適切で、このボタンは「バルーンを開く」ボタンではなく、「バルーンを開け閉めする」ボタン。だから `toggleBallon()` とかが適切！

2022-10-24 02:32 UTC, YuyaImanari commented on components/headerLoginAfter.vue
> +          console.log("ログアウトしました");
これはUXアドバイス。
`console.log()` よりも `alert()` の方が親切だと思う！

2022-10-24 02:32 UTC, YuyaImanari commented on components/headerLoginAfter.vue
> +            <span
ここ、ブロック要素の `div` じゃなくて、インライン要素の `span` にした理由ある？
あんまり見ない使い方だなあと思ったってだけなんだけど笑

2022-10-24 02:32 UTC, YuyaImanari commented on components/shopSearch.vue
> +    success(position) {
さすがに成功したときだってわかるからコメントは不要かな笑

ただ、この位置に `success()` を定義すると、何が成功したときに呼ばれるメソッドかわからない。

1. `getCurrentLatLng()` の中で `const success = () => {}` と定義する。
2. メソッド名を `successGetCurrentLatLng()` のようなメソッド名にする。

の2通りがあると思う。自分なら、記述量的にも前者にするかなあ

2022-10-24 02:32 UTC, YuyaImanari commented on components/shopSearch.vue
> +      this.searchPlace();
ここで `await` してもしなくても差ないけど、`this.searchPlace()` は非同期関数だから、一応 `await` してあげて欲しい。可読性の問題。

2022-10-24 02:32 UTC, YuyaImanari commented on components/shopSearch.vue
> +            if (place.access === null) {
今成は `let` が大嫌いなのでバカみたいに指摘しまくると思うけどご理解ください🙇‍♂️

456行目で宣言して、465〜469行目で代入していると思うけど、この1行で表現できます！

```javascript
const placeAccess = place.access ?? "";
```

唯一神 `const` 🤩

2022-10-24 02:32 UTC, YuyaImanari commented on components/shopSearch.vue
> +            if (place.photo.pc.l === null) {
仕様がわかっていないけど、`photo` が null とか undefined になることはないの？
もしあるなら、`place.photo?.pc?.l` にしないとエラー吐く。

2022-10-24 02:32 UTC, YuyaImanari commented on components/shopSearch.vue
> +          if (this.allDataNum === this.countNum) {
動いているからこれでもいいんだけど、ちょっとわかりにくいな……

「すべて検索する」っていうメソッドと、「100個検索する」っていうメソッドは分けて宣言した方が読みやすいコードになると思った。
（チーム開発なら直してもらったなあレベル、ちゃんと読めばわかるから）

2022-10-24 02:32 UTC, YuyaImanari commented on components/shopSearch.vue
> +      allDataNum: 1,
純粋な疑問なんだけど、なんで `allDataNum` の初期値1なの？

2022-10-24 02:32 UTC, YuyaImanari commented on layouts/default.vue
> +import HeaderLoginBefore from '~/components/headerLoginBefore.vue';
これは Nuxt.js の機能なんだけど、ディレクトリ構成に沿った名前で利用する場合は自動でインポートされているので `import` も `export default` 内の `components` も不要。

https://nuxtjs.org/docs/directory-structure/components/#components-discovery

2022-10-24 02:32 UTC, YuyaImanari commented on pages/login.vue
> +        userMail: null,
フォームの文字列を扱うなら、初期値は null じゃなくて 空文字列 `""` が適切

2022-10-24 02:32 UTC, YuyaImanari commented on pages/login.vue
> +      signForm: {
これは多分ケアレスミスだけど、`signupForm` だと思う

2022-10-24 02:32 UTC, YuyaImanari commented on pages/login.vue
> +      const resultEmail = await this.checkEmailLogin();
`this.checkEmailLogin()` も `this.checkPassLogin()` も同期関数だから、`await` 不要
→ `checkValidationLogin()` も `async` 不要で同期関数化可能
→ 呼び出し元も `await` 不要

2022-10-24 02:32 UTC, YuyaImanari commented on pages/login.vue
> +        firebase
`firebase.auth().signInWithEmailAndPassword()` は非同期処理なので、`await` がついていると親切。

てか、`firebase.auth()` は `~/service/firebaseService.js` でやらないのか

2022-10-24 02:32 UTC, YuyaImanari commented on pages/login.vue
> +            this.$store.dispatch("checkLogin");
これはこんがらさてしまいそうだから、すっと理解しなかったら無視してくれていいんだけど、、、

`signInWithEmailAndPassword()` の戻り値は `UserCredential` で、`UserCredential.user` に `uid`, `email`, `displayName` などが格納されている。だから、わざわざ、dispatch で `onAuthStateChanged()` する必要がなくて、State に代入する処理を commit すればいいのでは？って思った。

参考
[signinwithemailandpassword()](https://firebase.google.com/docs/reference/js/v8/firebase.auth.Auth#signinwithemailandpassword)
[UserCredential](https://firebase.google.com/docs/reference/js/v8/firebase.auth#usercredential)

【追記】
と思ったけど、312行目でやっている処理がまさにこれだわ。

> `signInWithEmailAndPassword()` の戻り値は `UserCredential` で、`UserCredential.user` に `uid`, `email`, `displayName` などが格納されている。

2022-10-24 02:32 UTC, YuyaImanari commented on pages/login.vue
> +      const resultUsername = await this.checkUsername();
この辺全部同期処理だから `await` 不要

2022-10-24 02:32 UTC, YuyaImanari commented on pages/login.vue
> +        /^[A-Za-z0-9]{1}[A-Za-z0-9_.-]*@{1}[A-Za-z0-9_.-]+.[A-Za-z0-9]+$/;
`imanari.yuya+1@letterfan.jp` が弾かれてしまった……

メールアドレスのバリデーションは、厳密には複雑すぎる → https://note.com/reflex4qa/n/n27fb36daa699
`signInWithEmailAndPassword()` も `createUserWithEmailAndPassword()` もしっかりとメールアドレスもパスワードもチェックしてもらえるので、自前でやる必要はそこまでないのかな〜って思ったり。

なので、やるべきなのは「空ではないか」「確認用の入力との一致」くらいかなあ

2022-10-24 02:32 UTC, YuyaImanari commented on pages/login.vue
> +      let UserMail = false;
ここ以降、ちょくちょく大文字から始まる変数名が出てくるけど、JSでは小文字から始めるキャメルケース（camelCase）に統一してください！

あと、変数名がよろしくなくて、`isPassedValidator` とかでいいんじゃない？

1. この変数名だと、メールアドレスが入っていそうだと思ってしまう
1. このメソッド (`checkEmailLogin`) 内であれば、メールアドレスのバリデーションを扱っているのは自明なので、変数名に `email` 要素は不要

→ そもそも変数で置く必要なくて、else 文のところで `return true;` して、その外で `return false;` すればいいだけな気もする。ちょっと複雑で可読性落ちるけど……

2022-10-24 02:32 UTC, YuyaImanari commented on services/firebaseService.js
> +          if (!doc.data()) {
この指摘は難しいところで、厳密にはif文に `{}` は必須という考え方もある。ただなくてもよいし、そっちの方がスッキリはする。

その上で、クエリに引っかかっている時点でドキュメントは存在しているので、snapshot に `doc.data()` が null の要素はない。このチェック不要。

他にも色んなところで不必要なチェックしている〜

2022-10-24 02:32 UTC, YuyaImanari commented on services/firebaseService.js
> +    favRef.doc().set({
ここ、`await` してあげないと、呼び出し元の非同期関数が処理を待たずに正常終了しちゃう。

2022-10-24 02:32 UTC, YuyaImanari commented on services/firebaseService.js
> +        activityCount: actCount,
### +1して更新する系の処理

```javascript
await activeCountRef.doc("count").update({
  activityCount: firebase.firestore.FieldValue.increment(1)
});
```

で可能。

[FieldValue | JavaScript SDK  |  Firebase JavaScript API reference](https://firebase.google.com/docs/reference/js/v8/firebase.firestore.FieldValue#increment)

あと、いつもの如く、`await` 忘れないで。

### バッチ処理

92行目からの `set()` 処理と、100行目からの `update()` 処理、どちらかだけ行われたら整合性取れなくなる！っていうときあるじゃん？そういうときにおすすめなのが、バッチ処理

[トランザクションとバッチ書き込み  |  Firestore  |  Firebase](https://firebase.google.com/docs/firestore/manage-data/transactions?hl=ja#batched-writes)

ちらっと読んでみて欲しい〜

2022-10-24 02:32 UTC, YuyaImanari commented on services/firebaseService.js
> +        activityCount: actCount,
ここもさっきのと同じで `firebase.firestore.FieldValue.increment(-1)` で可能

2022-10-24 02:32 UTC, YuyaImanari commented on services/firebaseService.js
> +            await doc.ref.delete();
`forEach()` 内の `await` は `await` してくれないという罠があるので気をつけてください。
ただ、ちょっと複雑なので、今度 `Promise.all()` について話します！

2022-10-24 02:32 UTC, YuyaImanari commented on services/firebaseService.js
> +  if (action === 'favorite') {
こういうまとめられるの、ちょこちょこあるのでチェックしてみて！

2022-10-24 02:32 UTC, YuyaImanari commented on store/index.js
> +  getData: function (state, payload) {
なぜか `mutations` の関数だけこの書き方している……
`getData(state, payload) {}` で大丈夫よ

2022-10-24 02:32 UTC, YuyaImanari commented on store/index.js
> +    login: false,
ここの変数名も微妙〜

2022-10-26 01:46 UTC, caramelribon commented
## 修正
- [] headerLoginAfter
- [] headerLoginBefore
- [] appRanking
- [] shopSearch

2022-10-30 02:22 UTC, caramelribon commented on components/headerLoginAfter.vue
> +            <span
特になかったので、`div`に直しました！

2022-10-30 02:26 UTC, caramelribon commented on components/shopSearch.vue
> +      allDataNum: 1,
`if(this.allDataNum === this.countNum)`になったら、お店の情報を繰り返し取得させるのをやめるようになっていて、初期値が両方とも0だと、このif文によって、お店の情報を取得できなくなるので、1にしていたんだと思います....

2022-10-31 09:26 UTC, YuyaImanari requested changes
@caramelribon 
いっぱいコメントしちゃいました……ごめんなさい🙏

### 直接書いていないところ

- store/index.js、結構な非同期処理が `await` されていないけど、問題ない？

2022-10-31 09:26 UTC, YuyaImanari commented on components/appRanking.vue
> +          const placeData = {
どうもワンライナーおじさんです🤓
このままでもいいけどワンポイントアドバイス。

1. element の key-value はそのまま placeData に引き継ぐならスプレッド構文（`...`）が使える
2. すぐ `return` するなら省略できる

```javascript
await getRankingTop("favorite")
  .then((result) => {
    this.favoriteRanking = result.map((element, index) => ({
      ...element,
      no: index + 1,
    }));
  })
  .catch((err) => {
    console.log("Can not get data of favorite ranking", err);
  });
```

スプレッド構文使わないならこんな感じかなあ

```javascript
await getRankingTop("favorite")
  .then((result) => {
    this.favoriteRanking = result.map((element, index) => {
      element.no = index + 1;
      return element;
    });
  })
  .catch((err) => {
    console.log("Can not get data of favorite ranking", err);
  });
```

### 備考

あと、上くらいの長さになるなら `getRankingTop("favorite")` と `getRankingTop("mark")` の `.then()` を2回書いてもいいけど、元コードくらい長くなるときは見通し悪いから関数化して呼び出した方が綺麗！

```javascript
const createRanking = (shops) =>
  shops.map((shop, index) => ({
    id: shop.id,
    name: shop.name,
    address: shop.address,
    access: shop.access,
    average: shop.average,
    catchcopy: shop.catchcopy,
    open: shop.open,
    photo: shop.photo,
    url: shop.url,
    no: index + 1,
  }));
this.favoriteRanking = await getRankingTop("favorite")
  .then(createRanking)
  .catch((err) => {
    console.log("Can not get data of favorite ranking", err);
    return [];
  });
this.bookmarkRanking = await getRankingTop("mark")
  .then(createRanking)
  .catch((err) => {
    console.log("Can not get data of bookmark ranking", err);
    return [];
  });
```

2022-10-31 09:26 UTC, YuyaImanari commented on components/appRanking.vue
> +      <div class="ranking pb-10">
これは1回目のレビューで指摘すべきだったけど、Faviorite と Bookmark のランキングはコンポーネント化して呼び出すべき！
`props` として `ranking` を渡すのが良さげ。

2022-10-31 09:26 UTC, YuyaImanari commented on components/shopSearch.vue
> +        async (position) => {
[このレビュー](https://github.com/caramelribon/sweets-journal-nuxtjs/pull/1#discussion_r1002816183) 受けてこうしてくれたんだよね？
とりあえずOK！
ただ、`success` と `error` に相当する部分が長くなると一気に可読性が落ちるので、一般的な書き方はこう。
今のコードは今のままで全然良い。

今成のイメージはこんな感じだった。

```javascript
getCurrentLatLng() {
  const onSuccess = async (position) => {
    this.lat = position.coords.latitude;
    this.lng = position.coords.longitude;
    this.radiusName = await this.checkRadius();
    this.genreName = await this.checkGenre();
    await this.firstSetting();
    await this.searchPlace();
  };
  const onError = () => {
    this.currentState = "IS_FAILED";
    console.log(error.message);
  };
  navigator.geolocation.getCurrentPosition(onSuccess, onError);
},
```

2022-10-31 09:26 UTC, YuyaImanari commented on components/shopSearch.vue
> +          await this.firstSetting();
[このレビュー](https://github.com/caramelribon/sweets-journal-nuxtjs/pull/1#discussion_r1002816473) 紛らわしくてごめん……

`await` は非同期処理が完了する（`Promise` が終了する）のを待ちたいときに、非同期関数の前に付けるもの。
つまり同期処理の前に付けても意味がない！
スクショを添付したけど、拡張機能 Vetur の機能として警告が出ていて、`'await' has no effect on the type of this expression.` と書かれている。

呼び出し元が同期関数か非同期関数かは気にして実装するとより良いコードになる！

<img width="1512" alt="cap 2022-10-31 15 54 42" src="https://user-images.githubusercontent.com/16618734/198949322-3a39419a-e4d7-452b-8016-28a3a25f62cc.png">

2022-10-31 09:26 UTC, YuyaImanari commented on components/shopSearch.vue
> +        ? "半径500m以内"
三項演算子激推ししておいて申し訳ないけど、2つ以上の三項演算子は見にくいので禁止！
元コードみたいに、if-else が良い
（switch 文という選択肢もあるけど、レターファンでは switch 文より if-else 推し）

2022-10-31 09:26 UTC, YuyaImanari commented on components/shopSearch.vue
> +        this.resultState = "NO_DATA";
フォーマッターかけて〜

2022-10-31 09:26 UTC, YuyaImanari commented on components/shopSearch.vue
> +          this.places = data.map((element) => {
後述の指摘で消されちゃうので無意味な指摘にはなってしまうけど……

ここで直接代入すると、そこまでの検索結果が上書きされちゃう。
具体的には、全部で110件あるとして、101〜110件目のときに、1〜100件目のデータが格納されている `this.places` を上書きしてしまう。
既存配列への結合は `concat()` を使ってください！

2022-10-31 09:26 UTC, YuyaImanari commented on components/shopSearch.vue
> +        await this.getPlaceData();
伝えたこと、しっかり実現していてくれて素晴らしい！

関数化（メソッド化）について意見があるので、長文になるけど読んで欲しい。
その上で、次回出社時でも良いし、時間があるときにハドルでも良いので説明させて！

関数には [カプセル化](https://ja.wikipedia.org/wiki/%E3%82%AB%E3%83%97%E3%82%BB%E3%83%AB%E5%8C%96) や [疎結合](https://e-words.jp/w/%E7%96%8E%E7%B5%90%E5%90%88.html) という大事な概念がある。うまく言葉にできないけど、今回のコードで説明すると、`searchPlace()` と `getPlaceData()` は依存し合わないし、`getPlaceData()` 内部の処理が変更されても `searchPlace()` には影響がない状態が望ましい。
現状、`searchPlace()` で利用している `this.getDataNum` や `this.allDataNum` が `getPlaceData()` で更新されているせいで、関数が分けられている恩恵を享受しきれていない。

また、Vue の `data()` メソッドで返している値（`this.hoge` でアクセスできるやつ）は、ある意味グローバル変数になっている。
そして、JS含め、プログラミング言語においてグローバル変数は悪。
どこから変更されているのかわからないので、意図しない変更が入るリスクがあり、可読性と保守性に超悪影響を及ぼすから。
Vue では `data()` メソッドで返している値は使い勝手が良いのでガンガン使うが、可読性や保守性を担保するために、「このメソッドからしか変更しませんよ」とか「読み込み時にセットした値から変更はありませんよ」とかなんとなく伝わってくるコードであることが嬉しい笑（曖昧な表現でごめん笑）

結論、こういう書き方になっていると非常に読みやすい。

```javascript
// countNum, startNum, allDataNum は data() から削除
// countNum -> placesTmpCnt に変更
async searchPlace() {
  let placesTmpCnt = 0;
  let allDataNum = -1;
  // TODO: getPlaceData() での例外処理を解除し、try-catch での例外処理が必要。
  // でないとエラーが発生すると while 文がいつまで経っても終わらない
  while (allDataNum !== placesTmpCnt) {
    const { places100, allDataNum } = await this.getPlaceData(placesTmpCnt);
    placesTmpCnt += places100.length;
    this.resultState = allDataNum ? "GET_DATA" : "NO_DATA";
    this.currentState = "IS_FOUND";
    this.places = this.places.concat(places100);
  }
},

async getPlaceData(placesCnt) {
  const startIdx = placesCnt + 1;
  const response = await this.$axios.$get(
    // 省略：startNum -> startIdx
  );
  // this.currentState の更新は searchPlace() へ
  const places100 = response.results.shop.map((place) => {
    // 省略
  });
  const allDataNum = response.results.total_returned;
  return { places100, allDataNum };
},
```

2022-10-31 09:26 UTC, YuyaImanari commented on services/firebaseService.js
> +        placeIdData.push(doc.data().place_id);
ワンライナーおじさん登場！
この形、よく使うので覚えておいて！
このファイルにも同じような形で書き換えられる箇所がいくつかあると思う。

```javascript
export const getUserServePlaceData = async (userId, action) => {
  const assignRef = action === "favorite" ? favRef : bmRef;
  const placeIdData = await assignRef
    .where("user_id", "==", userId)
    .get()
    .then((snapShot) => snapShot.docs.map((doc) => doc.get("place_id")))
    .catch((error) => {
      // 例外処理が必要なら例外処理
    });
  return placeIdData;
};
```

2022-10-31 09:26 UTC, YuyaImanari commented on services/firebaseService.js
> +    batch.delete(doc.ref);
`querySanpshot` って原則1件しかないはず？（`querySnapshot.size` は `1` ？）
なら、明示的に `querySnapshot.docs[0].ref` にしてもよいかも。

2022-10-31 09:26 UTC, YuyaImanari commented on services/firebaseService.js
> +      favorite_count: firebase.firestore.FieldValue.increment(-1),
ここは短縮しようぜ〜

Object の key に変数使うことできる！

```javascript
const key = "hoge";
const exObject = { [key]: "fuga" };
```

だから、`"favorite_count"` と `"bookmark_count"` は変数 `action` でまとめられる！

2022-10-31 09:26 UTC, YuyaImanari commented on services/firebaseService.js
> +      console.error("ログインエラー", error);
ここ、何か `return` しないと `userRegisteredData` が `undefined` になってしまうけど問題ない？
ほかも同様。

2022-11-01 02:50 UTC, YuyaImanari requested changes
#2 のレビューで指摘されていることまとめておいた

2022-11-01 02:50 UTC, YuyaImanari commented on store/index.js
> +  user: (state) => {
https://github.com/caramelribon/sweets-journal-nuxtjs/pull/2#discussion_r1009133291  で指摘

2022-11-01 02:50 UTC, YuyaImanari commented on services/firebaseService.js
> +  const activeDataRef = await activeRef.doc();
https://github.com/caramelribon/sweets-journal-nuxtjs/pull/2#discussion_r1009217744 で指摘

2022-11-05 00:16 UTC, YuyaImanari requested changes
@caramelribon これ直したら終わりで良さそう！
細かくてごめん〜

2022-11-05 00:16 UTC, YuyaImanari commented on components/appRanking.vue
> +      <ranking-design ranking= "mark" />
フォーマッターかけて〜

2022-11-05 00:16 UTC, YuyaImanari commented on layouts/default.vue
> +    <header-login-before v-if="!this.user.isLogin" />
`this` 不要！（うまくいかないはず）

2022-11-05 00:16 UTC, YuyaImanari commented on components/headerLoginAfter.vue
> +    }),
他のページと同じように

```javascript
...mapGetters(["users"])
```

でいいよ〜
（改行レベルの話だけど default.vue も）

2022-11-05 00:16 UTC, YuyaImanari commented on services/firebaseService.js
> +      return rankingDataDocs;
いつものようにワンライナーで申し訳ない。
適宜改行したり式を分けたりしてくれていいんだけど、これは分け過ぎだなあと思ったので指摘。
一行で書いたら見せて欲しい笑

2022-11-05 00:16 UTC, YuyaImanari commented on components/shopSearch.vue
> +      startNum: 1,
`countNum` と `startNum` は削除可能

2022-11-05 00:16 UTC, YuyaImanari commented on components/shopSearch.vue
> +      this.countNum = 0;
`startNum` と `countNum` は削除可能
`allDataNum` は未定義

2022-11-05 00:16 UTC, YuyaImanari commented on components/shopSearch.vue
> +      let allDataNum = -1;
PRレビューが間違ってた。ここの `allDataNum` 不要だわ。

2022-11-05 00:43 UTC, YuyaImanari approved these changes

2022-11-05 00:43 UTC, merged