ログインユーザのProfileページの作成
caramelribon/sweets-journal-nuxtjs pull request #2
Opened 2022-10-30 10:04 UTC by caramelribon

2022-10-31 09:53 UTC, golonyataro reviewed
お疲れ様！本田レビューです。
middleware、updateProfileの使い方知らなかったから勉強になった！
別の部分なんだけど、login.vueの189行目インデントバグってたからフォーマッターかけた方がいいかも！

2022-10-31 09:53 UTC, golonyataro commented on components/headerLoginAfter.vue
> +                        :to="`/users/${ $store.state.user.id}`"
下の指摘に同じ & フォーマッターお願いします！

2022-10-31 09:53 UTC, golonyataro commented on components/headerLoginAfter.vue
> +                    {{ $store.state.user.name }}
ちゃんとstoreから呼び出せていて素晴らしい！ですが、vuexにはmapGettersというヘルパーメソッドがあります。
mapGettersを使うとすごくシンプルにstoreの変数を呼び出せて便利です。下記記事を参考にして実装してみてください。

[Vue公式]
https://vuex.vuejs.org/ja/guide/getters.html#mapgetters-%E3%83%98%E3%83%AB%E3%83%91%E3%83%BC
[いい感じのQiita]
https://qiita.com/terufumi1122/items/6f9470c8d416a4af7502

2022-10-31 09:53 UTC, golonyataro commented on layouts/default.vue
> +    <header-login-before v-if="!$store.state.user.isLogin" />
同上

2022-10-31 09:53 UTC, golonyataro commented on middleware/auth.js
> +export default function ({store, redirect}) {
`export default (store, redirect) => {`
アロー関数使ってこう書けそう

2022-10-31 09:53 UTC, golonyataro commented on services/firebaseService.js
> +  console.log(userRegisterData);
デバッグ残し

2022-10-31 09:53 UTC, golonyataro commented on services/firebaseService.js
> +export const onSignUp = async (userMail, userPass, userName) => {
ここで定義しているonSingUp(onLoginも)をlogin.vueでインポートして使ってると思うんだけど、login.vueにも同名のメソッドが存在している。動作としては問題ないと思うけど、分かりづらいなと思ってしまったから別の名前で書いた方が良いかも

2022-10-31 09:53 UTC, golonyataro commented on services/firebaseService.js
> +export const onSignUp = async (userMail, userPass, userName) => {
@YuyaImanari

2022-10-31 09:53 UTC, golonyataro commented on services/firebaseService.js
> +  const activeDataRef = await activeRef.doc();
await不必要だし、変数名もactiveDocとかの方がいいかな

2022-10-31 09:53 UTC, golonyataro commented on services/firebaseService.js
> +  const activeCountDataRef = await activeCountRef.doc("count");
同上

2022-10-31 09:53 UTC, golonyataro commented on services/firebaseService.js
> +  const placeDataRef = await placeRef.doc(placeId);
同上

2022-10-31 09:53 UTC, golonyataro commented on store/index.js
> +  user: (state) => {
```
user (state) {
  return state.user
}
```
でも動くよっていうメモ！

2022-11-01 00:33 UTC, YuyaImanari commented on components/headerLoginAfter.vue
> +                    {{ $store.state.user.name }}
補足！

### state と getters
そもそも state への直接アクセスと getters 経由での取得って何が違うのか？
一緒です。似たレベル感の違いだと、マスタッシュ構文 `{{ hoge }}` で計算するか`computed` を用いるか、とか。

レターファンでは、state に直接触れることはありません。ほぼ同じなのに getters 用意するんかい！って感じはあるけど。
無理やり理由をつけるとすれば、Vuexからのデータ取得は getters を使うと縛ると、mutations を介さない state の直接書き換えなどが起こるリスクが低減する。

呼び出し方はほぼ同じで `$store.getters.user` です。

### state のヘルパー

`mapGetters` は getters のヘルパーですが、state にも `mapState` というヘルパーがある。
→ https://vuex.vuejs.org/ja/guide/state.html#mapstate-%E3%83%98%E3%83%AB%E3%83%91%E3%83%BC

### クラシックモードとモジュールモード

Vuex についてググると、書き方の違う記法が出てくることがあります。これはモードが違うからなので、あまり気にしないでください。

解説：https://develop365.gitlab.io/nuxtjs-2.8.X-doc/ja/guide/vuex-store/
公式ドキュメントはわかりにくいです：https://vuex.vuejs.org/ja/guide/modules.html

※ @golonyataro state を mapGetters に書き換えよう！は話が若干飛躍してる😔

2022-11-01 00:36 UTC, YuyaImanari commented on services/firebaseService.js
> +  console.log(userRegisterData);
ここに限らずそこら中に `console.log()` あるよね。
プロダクトとして世に出すときは `console.log()` は極力消さなければいけない。邪魔だから笑
でもこのプロダクトに関しては任せる。超量多いし、`console.log()` 消すのに時間使ってたらもったいないから。

余談。
でも実装中は見たい！とかテスト環境では見たい！みたいなこともあるので、開発環境でのみコンソールに出力される `customeConsoleLog()` 的なメソッド作ることもある。

2022-11-01 02:37 UTC, YuyaImanari commented on services/firebaseService.js
> +export const onSignUp = async (userMail, userPass, userName) => {
物理でありがちな `v = v のとき` 的なね。物理初学者には厳しい。

冗談は置いておいて……
まず、一般論から。`this.hoge` と `hoge` の共存とか、`self.fuga` と `fuga` の共存とかはよくあることなのでそこまで気にすることではない。

ただ、今回に関して言うと、login.vue の `import { onSignUp, onLogin } from "~/services/firebaseService";` のようにモジュールを読み込むのはあまり綺麗じゃない。なぜなら、`~/services/firebaseService` が FirebaseService クラスのような振る舞いができているから。

```javascript
// named export なら
export const FirebaseService = {
  onLogin,
  // 省略
};

// default export なら
export default FirebaseService = {
  onLogin,
  // 省略
};
```

```javascript
import FirebaseService from "~/services/firebaseService";
// ↓このように使う
FirebaseService.onLogin();
```

こっちのほうが、何のモジュールを使っているか書かれていてわかりやすい！

### 補足

named export と default export について
- named export 派
  -  https://engineering.linecorp.com/ja/blog/you-dont-need-default-export/
- default export 派
  - https://zenn.dev/yuhr/articles/668dba202726bf#基本的にdefault-exportのみを使うべき
  - https://blog.uhy.ooo/entry/2021-09-09/answer-named-export/

社内で明確な基準はまだ設けられていないけど、モジュール的に使う場合は default export 派

2022-11-01 02:43 UTC, YuyaImanari commented on services/firebaseService.js
> +  const activeDataRef = await activeRef.doc();
変数名に関して補足。別にこれでも良いなあとは思う笑
ただ、型が `DocumentReference` なので、変数名は `activeDocRef` が最も適切だと思う。


ちなみに、レターファン社内では

- CollectionReference ：hogesRef
- CollectionSnapshot：hogesSnapshot
- DocumentReference：hogeDocRef
- DocumentSnapshot：hogeDoc

みたいに書くことが多いかな。（だから、本田は `activeDoc` を推した）

2022-11-01 02:49 UTC, YuyaImanari commented on store/index.js
> +  user: (state) => {
補足

公式ドキュメントは https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions/Method_definitions#%E8%A7%A3%E8%AA%AC
（多分）ES2015で追加された機能で、こっちのほうが `this` の取り扱いとかが容易なので、基本こっちを使って欲しい。

2022-11-01 05:50 UTC, YuyaImanari requested changes
@caramelribon #1 と被っていない範囲でレビューした！
#1 の修正からお願いします〜

2022-11-01 05:50 UTC, YuyaImanari commented on services/firebaseService.js
> +          if (!place) return;
ドキュメントIDを指定して DocumentSnapshot を取得すると、そのドキュメントの有無に関わらずオブジェクトが入った状態で返される。
したがって `!place` は常に false になってしまうので、`!place.exists` でチェックして欲しい！

2022-11-01 05:50 UTC, YuyaImanari commented on services/firebaseService.js
> +        placeRef.doc(placeId).get().then((place) => {
ここ `await` しないと `placeData` 空になる気がするんだけど、どうだろう？
ただ、`forEach` の中で `await` 使っても効力がないという超罠があるので、`Promise.all()` という技を覚えないといけない。
書くの面倒だから、次回説明する！

2022-11-01 05:50 UTC, YuyaImanari commented on pages/users/_id.vue
> +              <div class="m-4 card animate__animated animate__fadeInUp">
https://github.com/caramelribon/sweets-journal-nuxtjs/pull/1#discussion_r1009074994 でコンポーネント化したら？ってアドバイスしたのとほぼ同じ構成かな？

いずれにせよ `activeTab === 'favorite'` と `activeTab === 'bookmark'` でコンポーネント化すべき。

2022-11-06 03:11 UTC, YuyaImanari requested changes
@caramelribon ほぼOK！
直したらマージしちゃお

2022-11-06 03:11 UTC, YuyaImanari commented on services/firebaseService.js
> +  const registeredPlaceData = await Promise.all(promises);
199行目の `if (!placeDoc.exists) return;` に引っかかった場合、その要素は undefined で配列 `registeredPlaceData` に入れられるけど、問題ない？
- そもそも `placeDoc.exists` が false になることはない → 199行目不要
- 問題ない → このままでOK
- 問題あり → `const registeredPlaceData = (await Promise.all(promises)).filter(el => el);` で undefined を配列要素から消せる

2022-11-06 03:11 UTC, YuyaImanari commented on pages/users/_id.vue
> +    async created() {
フォーマッターかける癖つけよう！

2022-11-06 03:11 UTC, YuyaImanari commented on pages/users/_id.vue
> +      this.$store.dispatch("onFavorite", place);
この処理は非同期処理なので

- `onFavorite` の成功失敗を待たず、とりあえずいいね印は付けたい → 209〜214行目を先に処理して207行目を書いた方がわかりやすい
- `onFavorite` の成功したときのみいいね印は付けたい → `await` 必須

2022-11-06 03:50 UTC, merged